# -*- coding: utf-8 -*-
"""new_semproject

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xznh5oPFhfUpbkVtvPZT3eJH4wAcYmZ5
"""

#!sudo apt-get update && sudo apt-get install -y zstd

#!curl -fsSL https://ollama.com/install.sh | sh

#!pip install ollama wn

import subprocess
import threading
import time
#import ollama

def run_ollama():
    subprocess.Popen(["ollama", "serve"])

thread = threading.Thread(target=run_ollama)
thread.daemon = True
thread.start()
time.sleep(5)

#!ollama pull llama3

import wn
wn.download('oewn:2024')
ewn = wn.Wordnet('oewn:2024', lang='en')

import subprocess
import threading
import time
#import ollama
import argparse
import logging
import re
import json
from ollama import generate
import os
from collections import Counter
import datetime
import statistics
from tqdm import tqdm

logger = logging.getLogger(__name__)

def parse_arguments():
    parser = argparse.ArgumentParser(description="Tag concepts in the JSON corpus using ollama and wordnet.")
    parser.add_argument("range", help="The range of text to tag, in the format from:to")
    parser.add_argument("json_file", help="Path to the JSON corpus file")
    parser.add_argument("--dry-run", action="store_true", help="Print the selected tags without updating JSON")
    parser.add_argument("-m", "--model", default="gemma2:9b", help="Ollama model (default: gemma2:9b)")
    parser.add_argument("--wn-only", action="store_true", help="Use only WordNet meanings, exclude additional tags")
    parser.add_argument("--verbose", action="store_true", help="Enable verbose output for detailed logging")
    parser.add_argument("--context", type=int, default=2, help="Number of sentences before and after to include in context (default: 2)")
    return parser.parse_args()

def generate_and_extract(prompt, model='gemma2:9b'):
    result = generate(model=model, prompt=prompt, options={"temperature": 0.0})
    response = result['response'].strip()
    think_match = re.search(r'<thinking>(.*?)</thinking>', response, re.DOTALL)
    if think_match:
        thinking = think_match.group(1).strip()
        cleaned_response = re.sub(r'<thinking>.*?</thinking>', '', response, flags=re.DOTALL).strip()
    else:
        thinking = None
        cleaned_response = response.strip()
    return thinking, cleaned_response
    key_match = re.search(r'(?:KEY:\s*)?([a-z]+|oewn-\d+-[nvasr]|per|loc|org|oth|x|w|e|num|dat|year|bio)', response, re.IGNORECASE)
    if key_match:
        selected_key = key_match.group(1).lower().strip()
    else:
        words = re.findall(r'\b(oewn-\d+-[nvasr]|[a-z]{1,4})\b', response.lower())
        selected_key = words[0] if words else None
    
    logger.info(f"Raw response: {response[:200]}...")
    logger.info(f"Extracted key: '{selected_key}'")
    
    return thinking, selected_key

def load_corpus(json_path):
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    print(f"Loaded: {len(data.get('sent', {}))} sentences, {len(data.get('conc', {}))} concepts")
    return data

def get_sentences_and_concepts(data, min_sid, max_sid):
    sentences = []
    for sid_str, sent_data in data.get('sent', {}).items():
        sid = int(sid_str)
        if min_sid <= sid <= max_sid:
            sent = sent_data.copy()
            sent['sid'] = sid
            sent['concepts'] = data.get('conc', {}).get(sid_str, {})
            sentences.append(sent)
    return sentences

def get_sids(from_sid, to_sid, margin):
    return list(range(from_sid - margin, to_sid + margin + 1))

def process_concept(concept, wn_lang='en', args=None):
    lemma = concept['clemma']
    meanings = {}

    synsets = ewn.synsets(lemma)

    for ss in synsets:
        defn = ss.definition() or ""
        lemmas = ", ".join(ss.lemmas())
        examples = "; ".join(ss.examples()) if ss.examples() else ""
        example_text = f" ({examples})" if examples else ""
        meanings[ss.id] = f"[{lemmas}] {defn}{example_text}"

    if args is None or not args.wn_only:
        meanings.update({
            'per': 'name of a person not in wordnet (_Irene_ arrived. Captain _Vantoch_ laughed.)',
            'org': 'name of an organization not in wordnet (I work at _IBM_)',
            'dat': 'date/time that is not in wordnet (It starts at _2pm_)',
            'loc': 'name of a place not in wordnet (We study in _Olomouc_)',
            'oth': 'other name not in wordnet (I use a _Thinkpad_)',
            'year': 'name of a year not in wordnet (I was born in _1967_)',
            'num': 'number not in wordnet (There were _42_ of them)',
            'e': 'the word was not tokenized or lemmatized correctly (\'I saw three _does_\' lemmatized as _do_ not _doe_)',
            'w': 'wordnet does not have the correct sense (\'I program in _python_\' meaning \'the computer language\')',
            'x': 'this is a closed class word (preposition, dummy it/there, relative pronoun, passive or progressive be/have, punctuation, love catlove youloveloa...). Or it is part of a multiword expression or it is an inappropriate multiword expression. (\'Kim scored a _hat_ trick\' _hat_ should be part of _hat trick_)'
        })


    return lemma, meanings

def construct_prompt(context, lemma, meanings):
    options = "\n".join([f"{key}: {value}" for key, value in meanings.items()])
    return f"""You are a precise linguistic annotator doing word sense disambiguation.

Context (several sentences around the target word):
> {context}

Target lemma: _{lemma}_

Choose **exactly one** label from the list below that best fits the lemma in this context.
If none of the WordNet senses fit well, prefer the special tags (per, loc, org, oth, w, x, e, bio, etc.).

Rules:
- per/loc/org/oth — proper names (people, places, organizations, other)
- w - only if NO WordNet sense fits
- x - function words, closed-class, multi-word parts
- e - tokenization/lemmatization error only
- Be conservative: prefer special tags over rare WordNet senses

Options:
{options}
Output format (strictly follow):
KEY: <the chosen key only>

Examples of correct output:
KEY: per
KEY: oewn-12345678-n
KEY: x
Your answer must be one line: KEY: <label>. No other text.
"""

def construct_context(index, sentences, context_size):
    start = max(0, index - context_size)
    end = index + 1 
    
    context_texts = [sent.get('text', '') for sent in sentences[start:end]]
    return ' '.join(context_texts)

def disambiguate(context, lemma, meanings, model_name):
    prompt = construct_prompt(context, lemma, meanings)
    logger.debug(f"Prompt: {prompt}")

    schema = {
        "type": "object",
        "properties": {"key": {"type": "string", "enum": list(meanings.keys())}},
        "required": ["key"],
    }
    try:
        result = generate(model=model_name, prompt=prompt, format=schema)
        response_json = json.loads(result['response'])
        key = response_json.get('key', '').strip()

        if key in meanings:
            logger.info(f"Structured success: '{key}'")
            return key, meanings[key]
    except Exception as e:
        logger.debug(f"Structured output failed ({e}), falling back to text parsing")

    thinking, cleaned_response = generate_and_extract(prompt, model=model_name)
    if thinking is not None:
        logger.debug(f"Model thinking: {thinking}")
    logger.info(f"Model response: {cleaned_response}")
    selected_key = extract_key(cleaned_response, meanings)
    if selected_key in meanings:
        return selected_key, meanings[selected_key]
    return None, None

def sentimentalize(context, lemma, model, gloss=''):
    if gloss:
        gloss = f' ({gloss})'
    sentiment_prompt = f"""You are assigning lexical sentiment ONLY for the word itself in isolation, NOT the overall sentence sentiment.

Target word: _{lemma}_ {gloss}

Context (for disambiguation only, ignore for sentiment value):
> {context}

Assign a number from -100 to +100 representing inherent sentiment of this lexical item:
  0   = neutral (most words, all technical/biological terms, names, numbers)
 +34  = mildly positive
 +64  = clearly positive (good, nice, great…)
 +95  = very positive (fantastic, wonderful…)
-34  = mildly negative
-64  = clearly negative (bad, poor…)
-95  = very negative (awful, terrible…)

Rules:
- Names of people, places, organizations - almost always 0
- Scientific / biological terms (species, anatomy, etc.) - 0
- Do NOT take irony, context modifiers, or story tone into account
- Evaluate the lemma as a dictionary entry, not as it appears in this particular sentence

First think briefly in <thinking>...</thinking>, then output ONLY the number.
"""
    thinking, sentiment_response = generate_and_extract(sentiment_prompt, model)
    logger.debug(f"Sentiment prompt: {sentiment_prompt}")
    if thinking:
        logger.debug(f"Model thinking: {thinking}")
    logger.info(f"Sentiment response: {sentiment_response}")
    try:
        score = float(sentiment_response)
    except ValueError:
        score = None
    return score

def main(range_str, json_file, model, context_window_size, dry_run, verbose, wn_only):
    logging.basicConfig(level=logging.DEBUG if verbose else logging.INFO)
    logging.getLogger("httpx").setLevel(logging.WARNING)

    class DummyArgs:
        def __init__(self, wn_only_val):
            self.wn_only = wn_only_val

    local_args = DummyArgs(wn_only)
    data = load_corpus(json_file)
    from_sid, to_sid = map(int, range_str.split(':'))
    sids = get_sids(from_sid, to_sid, context_window_size)
    sentences = get_sentences_and_concepts(data, min(sids), max(sids))
    total_concepts = sum(len(s['concepts']) for s in sentences)
    print(f"Processing {total_concepts} concepts with context_size={context_window_size}...")

    tagged = {}
    run_stats = {
        'context_size': context_window_size,
        'start_time': datetime.datetime.now().isoformat(),
        'processed_sentences': 0,
        'total_concepts': total_concepts,
        'tag_counts': Counter(),
        'sentiments': [],
        'non_zero_sentiments': 0,
        'per_sentence': {}
    }

    for i, sentence in tqdm(enumerate(sentences), total=len(sentences), desc="Sentences"):
        if sentence['sid'] < from_sid or sentence['sid'] > to_sid:
            continue

        text_context = construct_context(i, sentences, context_window_size)
        sid_str = str(sentence['sid'])
        tagged[sid_str] = {'concepts': {}}

        context_word_count = len(text_context.split())

        sentence_stats = {
            'sid': sentence['sid'],
            'context_sentences': len(text_context.split()) // 20 + 1,
            'context_words': context_word_count,
            'concept_count': len(sentence['concepts']),
            'tags': [],
            'sentiments': []
        }

        for sub_concept_key, concept_data_dict in sentence['concepts'].items():
            lemma, meanings = process_concept(concept_data_dict, args=local_args)
            selected_key, selected_value = disambiguate(text_context, lemma, meanings, model)
            sentiment = None
            if selected_key and selected_key not in ['x', 'e']:
                sentiment = sentimentalize(text_context, lemma, model, selected_value)

            print(f"\nSID {sid_str}, Sub-Concept Key: {sub_concept_key}:")
            print(f"  Lemma: {lemma}")
            print(f"  Context words: {context_word_count}")
            print(f"  Selected key: {selected_key}")
            if selected_key:
                print(f"  Selected value: {selected_value[:100]}...")
                if sentiment is not None:
                    print(f"  Sentiment: {sentiment}")
            print("-" * 60)

            if not dry_run:
                tagged[sid_str]['concepts'][sub_concept_key] = {
                    'clemma': lemma,
                    'tag': selected_key,
                    'sentiment': sentiment
                }

            if selected_key:
                run_stats['tag_counts'][selected_key] += 1
                sentence_stats['tags'].append(selected_key)

            if sentiment is not None:
                run_stats['sentiments'].append(sentiment)
                sentence_stats['sentiments'].append(sentiment)
                if sentiment != 0:
                    run_stats['non_zero_sentiments'] += 1

        run_stats['processed_sentences'] += 1
        run_stats['per_sentence'][sid_str] = sentence_stats

    run_stats['end_time'] = datetime.datetime.now().isoformat()
    if run_stats['sentiments']:
        sentiments_list = run_stats['sentiments']
        run_stats['sentiment_stats'] = {
            'mean': statistics.mean(sentiments_list),
            'median': statistics.median(sentiments_list),
            'min': min(sentiments_list),
            'max': max(sentiments_list),
            'count_non_zero': run_stats['non_zero_sentiments']
        }

    #summarz
    print("\n" + "="*60)
    print(f"STATISTICS FOR CONTEXT SIZE = {context_window_size}")
    print(f"Processed sentences: {run_stats['processed_sentences']}")
    print(f"Total concepts: {run_stats['total_concepts']}")

    print("\nTag distribution:")
    for tag, count in sorted(run_stats['tag_counts'].items(), key=lambda x: x[1], reverse=True):
        print(f"  {tag:>12}: {count:>4}")

    if 'sentiment_stats' in run_stats:
        ss = run_stats['sentiment_stats']
        print("\nSentiment statistics:")
        print(f"  Mean: {ss['mean']:.2f}")
        print(f"  Median: {ss['median']:.2f}")
        print(f"  Min/Max: {ss['min']}/{ss['max']}")
        print(f"  Non-zero count: {ss['count_non_zero']}")

    print("="*60 + "\n")

    #save tagged data
    if not dry_run:
        base_name = os.path.splitext(json_file)[0]
        output_path = f"{base_name}_tagged_context{context_window_size}.json"

        data_tagged = {
            "meta": {},
            "sent": {},
            "conc": {}
        }

        if "meta" in data:
            data_tagged["meta"] = data["meta"].copy()
        data_tagged["meta"]["annotator"] = f"ollama-{model}"
        
        for sid_str, updates in tagged.items():
            if sid_str in data.get('sent', {}):
                data_tagged['sent'][sid_str] = data['sent'][sid_str].copy()
                
            data_tagged['conc'][sid_str] = {}
            
            orig_concepts = data.get('conc', {}).get(sid_str, {})
            for cid, concept_info in updates['concepts'].items():
                if cid in orig_concepts:
                    new_concept = orig_concepts[cid].copy()
                    new_concept['tag'] = concept_info['tag']
                    if concept_info['sentiment'] is not None:
                        new_concept['sentiment'] = concept_info['sentiment']
                    
                    data_tagged['conc'][sid_str][cid] = new_concept
                    
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(data_tagged, f, indent=2, ensure_ascii=False)
        print(f"Tagged JSON saved to: {output_path}")

        #stats
        stats_path = f"{base_name}_stats_context{context_window_size}.json"
        with open(stats_path, 'w', encoding='utf-8') as f:
            json.dump(run_stats, f, indent=2, ensure_ascii=False)
        print(f"Statistics saved to: {stats_path}")

#test diff context sizes
context_sizes = [0, 1, 2, 3]
for size in context_sizes:
    print(f"\n=== Testing context size {size} ===")
    main(
        range_str="110001:110007",
        json_file="twwtn-en_human (1).json",
        model="ministral-nemo:12b",
        context_window_size=size,
        dry_run=False,
        verbose=True,
        wn_only=False
    )

#evaluation 
import nltk
from nltk.corpus import wordnet as nltk_wn
from collections import defaultdict

try:
    nltk.data.find('corpora/wordnet')
except LookupError:
    nltk.download('wordnet')

MISSING = "MISSING"

def tag_to_synset(tag):
    if not tag or not isinstance(tag, str) or tag.lower() == "none" or "-" not in tag:
        return None
    try:
        # format oewn-12345678-n
        parts = tag.split("-")
        if len(parts) >= 3 and parts[0] == "oewn":
            offset = int(parts[1])
            pos = parts[2].lower()
            return nltk_wn.synset_from_pos_and_offset(pos, offset)
        else:
            offset, pos = tag.rsplit("-", 1)
            pos = pos.lower()
            return nltk_wn.synset_from_pos_and_offset(pos, int(offset))
    except Exception:
        return None

def near_miss_from_tags(tag_gold, tag_pred):
    s1 = tag_to_synset(tag_gold)
    s2 = tag_to_synset(tag_pred)
    if s1 and s2:
        return s1.wup_similarity(s2)
    return None

def evaluate(target_path, gold_path):
    with open(target_path, "r", encoding="utf-8") as f:
        target = json.load(f)
    with open(gold_path, "r", encoding="utf-8") as f:
        gold = json.load(f)

    correct = 0
    total = 0
    tag_type_total = {}
    tag_correct_total = {}
    confusion_pos = defaultdict(lambda: defaultdict(int))
    confusion_synset = defaultdict(lambda: defaultdict(int))

    errors = defaultdict(int)
    near_miss_scores = []
    error_examples = []

    weighted_tp = 0.0
    weighted_fp = 0.0
    weighted_fn = 0.0

    correct_no_x = 0
    total_no_x = 0

    for group_name in target.get("conc", {}):
        target_group = target["conc"][group_name]
        gold_group = gold.get("conc", {}).get(group_name, {})

        if not gold_group:
            continue

        for item_name in target_group:
            target_item = target_group[item_name]
            gold_item = gold_group.get(item_name)

            if not gold_item:
                continue

            tag_g = gold_item.get("tag")
            
            if tag_g is None or str(tag_g).lower() == "none":
                continue

            tag_t = target_item.get("tag") if target_item else None
            
            # if pred tag is empty - missing 
            if tag_t is None or str(tag_t).lower() == "none":
                 tag_t = None

            if not target_item or not tag_t:
                errors["missing_target_tag"] += 1
                g_pos = tag_g.split("-")[-1] if "-" in tag_g else tag_g
                t_pos = MISSING
                confusion_pos[g_pos][t_pos] += 1
                total += 1
                tag_type_total[g_pos] = tag_type_total.get(g_pos, 0) + 1
                weighted_fn += 1
                continue 

            g_pos = tag_g.split("-")[-1] if "-" in tag_g else tag_g
            t_pos = tag_t.split("-")[-1] if "-" in tag_t else tag_t

            if g_pos != "x":
                total_no_x += 1
                if str(tag_g).strip().lower() == str(tag_t).strip().lower():
                    correct_no_x += 1

            confusion_pos[g_pos][t_pos] += 1

            general_tag = ["num", "oth", "per", "loc", "org", "e", "w", "dat", "year"]

            total += 1
            tag_type_total[g_pos] = tag_type_total.get(g_pos, 0) + 1

            gold_syn = tag_to_synset(tag_g)
            pred_syn = tag_to_synset(tag_t)

            if g_pos != t_pos:
                weighted_fp += 1
                weighted_fn += 1
            else:
                score = near_miss_from_tags(tag_g, tag_t)
                if score is None:
                    if str(tag_g).strip().lower() != str(tag_t).strip().lower():
                        weighted_fp += 1
                        weighted_fn += 1
                    else:
                        weighted_tp += 1.0 
                elif score >= 0.9:
                    weighted_tp += 1.0
                elif score >= 0.8:
                    weighted_tp += 0.7
                    weighted_fp += 0.3
                    weighted_fn += 0.3
                elif score >= 0.7:
                    weighted_tp += 0.4
                    weighted_fp += 0.6
                    weighted_fn += 0.6
                else:
                    weighted_fp += 1
                    weighted_fn += 1

            if str(tag_g).strip().lower() == str(tag_t).strip().lower():
                correct += 1
                tag_correct_total[g_pos] = tag_correct_total.get(g_pos, 0) + 1
            else:  
                if tag_t in general_tag and tag_g not in general_tag:
                    errors["coarse_tag"] += 1
                elif tag_t not in general_tag and tag_g in general_tag:
                    errors["generalized_tag"] += 1
                elif g_pos != t_pos:
                    errors["mismatch_pos"] += 1
                elif gold_syn and pred_syn and gold_syn.offset() != pred_syn.offset():
                    errors["mismatch_offset"] += 1
                else:
                    errors["unknown_tag"] += 1

                if (g_pos == t_pos and tag_g not in general_tag and tag_t not in general_tag):
                    score = near_miss_from_tags(tag_g, tag_t)

                    error_examples.append({
                        "group": group_name,
                        "item": item_name,
                        "gold_tag": tag_g,
                        "pred_tag": tag_t,
                        "gold_synset": gold_syn,
                        "pred_synset": pred_syn,
                        "near_miss": score
                        })
                    if score is not None:
                        near_miss_scores.append(score)
        
            g_key = gold_syn.name() if gold_syn else tag_g
            t_key = pred_syn.name() if pred_syn else tag_t

            if g_key != MISSING and t_key != MISSING:
                confusion_synset[g_key][t_key] += 1

    print(f"\n\033[1m---Total accuracy---\033[0m")
    accuracy = correct / total if total > 0 else 0
    print(f"{accuracy:.2%} correct ({correct}/{total})\n")
    
    print("\n\033[1m---Accuracy without x---\033[0m")
    acc_no_x = correct_no_x / total_no_x if total_no_x > 0 else 0
    print(f"{acc_no_x:.2%} correct ({correct_no_x}/{total_no_x})")

    # summary
    macro_precision = macro_recall = macro_f1 = 0.0
    tags_count = 0
    tp_total = fp_total = fn_total = 0
    
    all_tags = sorted(set(confusion_pos.keys()) | {t for preds in confusion_pos.values() for t in preds})

    for tag in all_tags:
        tp = confusion_pos[tag].get(tag, 0)
        fp = sum(confusion_pos[g].get(tag, 0) for g in all_tags if g != tag)
        fn = sum(confusion_pos[tag].get(t, 0) for t in all_tags if t != tag)

        tp_total += tp
        fp_total += fp
        fn_total += fn

        if tp + fp == 0 or tp + fn == 0:
            continue

        precision = tp / (tp + fp)
        recall = tp / (tp + fn)
        f1 = (2 * precision * recall / (precision + recall) if precision + recall > 0 else 0.0)

        macro_precision += precision
        macro_recall += recall
        macro_f1 += f1
        tags_count += 1

    if tags_count > 0:
        macro_precision /= tags_count
        macro_recall /= tags_count
        macro_f1 /= tags_count

    micro_precision = tp_total / (tp_total + fp_total) if tp_total + fp_total > 0 else 0
    micro_recall = tp_total / (tp_total + fn_total) if tp_total + fn_total > 0 else 0
    micro_f1 = (2 * micro_precision * micro_recall / (micro_precision + micro_recall) if micro_precision + micro_recall > 0 else 0)

    print("\n\033[1m---F1 Summary---\033[0m")
    print("Type".ljust(10), "Precision".rjust(10), "Recall".rjust(10), "F1".rjust(10))
    print(f"Macro".ljust(10), f"{macro_precision:>10.3f}", f"{macro_recall:>10.3f}", f"{macro_f1:>10.3f}")
    print(f"Micro".ljust(10), f"{micro_precision:>10.3f}", f"{micro_recall:>10.3f}", f"{micro_f1:>10.3f}")


print("EVALUATION FOR ALL CONTEXT SIZES")

gold_file = "twwtn-en_human (1).json"
for i in range(4):
    pred_file = f"twwtn-en_human (1)_tagged_context{i}.json"
    if os.path.exists(pred_file):
        print(f"\n\n>>> Evaluating Context {i} <<<")
        evaluate(pred_file, gold_file)
    else:
        print(f"\nFile not found: {pred_file}")
